### ISSUE TITLE
Queen and King are Switched on both sides

### ISSUE THREAD

**Issue by Synchronicity89** [Quinn-Barber/ChessEngine-QBarber-YHmaiti#2]
Queen and King are Switched on both sides

**Comment by YHmaiti** [comment]
thanks for pointing that out, we will fix it!

**Comment by cryptokonamicode** [comment]
Fixed in a fork, just needs approval to merge

**Comment by Quinn-Barber** [comment]
Thanks, I will look into rebuilding the project for GitHub pages, if you want to try it as well go for it!
